### ISSUE TITLE
Mismatch between assembler/simulator and encoding.txt 

### ISSUE THREAD

**Issue by korreman** [kirkedal/compSys-e2017-sim#14]
The encoding.txt file describes the following instruction encoding:
`movq i(%b),%a 0x50 ab ii ii ii ii`

Running the assembler with the instruction (first is for reference) yields the following result
`00000             40 AB 00 00 00 00 | 		movq %r10, (%r11)`
`00006             50 AB 00 00 00 00 | 		movq (%r10), %r11`

But the encoding specifies that the resullt should be
`00000             40 AB 00 00 00 00 | 		movq %r10, (%r11)`
`00006             50 BA 00 00 00 00 | 		movq (%r10), %r11`

The simulator runs successfully with the output from the assembler as well.

**Comment by ericqzou** [comment]
Korreman:
I did notice this before, actually the encoding file says the PRINTED RESULT shall still be AB, just as you have showed. But for some reason the encoding.txt has chosen to be consistent with the text book in DESCRIPTION of what the instruction does, when it describes simulated-encoding (Page 393). I admit that it may be a little confusing. For the didactic aspect, we will discuss this. Thank you for reminding us that.

**Comment by finnschiermer** [comment]
I'm a bit confused. The way I understand it, this has been fixed and can be closed. Please reopen if you don't think it has been fixed.
