### ISSUE TITLE
Better error messages when -m of -prof are missing

### ISSUE THREAD

**Issue by steffenvan** [kirkedal/compSys-e2017-sim#20]
Hej Finn, 

Når jeg prøver at køre kommandoen: 

    ./sim matrixmult-big.o -dc:idxsz=8 

får jeg denne fejlbesked:

    Argument error. Unknown option: '-dc:idxsz=8'

Samme gælder for alle relevante tal som inputs. Har fået besked fra Nis om at oprette dette issue.

Mvh
Steffen

**Comment by finnschiermer** [comment]
Fixed directly in master by improved error message.
